version: '3.5'

services:
  ambassador:
    image: quay.io/datawire/ambassador:0.74.1
    ports:
    # expose port 8080 via 8080 on the host machine
    - 8080:8080
    volumes:
    # mount a volume where we can inject configuration files
    - ./ambassador/config:/ambassador/ambassador-config
    environment:
    # don't try to watch Kubernetes for configuration changes
    - AMBASSADOR_NO_KUBEWATCH=no_kubewatch

  app:
    image: gcr.io/google_containers/echoserver:1.4

  oathkeeper:
    command: ["serve", "api", "-c", "/oathkeeper/config.yaml"]
    image: oryd/oathkeeper:v0.17.4-beta.1
    volumes:
    - ./oathkeeper:/oathkeeper

  oauth2-introspection:
    image: secure-api-gateway:oauth2-introspection
